{{- if .Values.enable_notifications }}
apiVersion: v1
kind: Secret
metadata:
  name: message-secrets
type: Opaque
stringData:
  twilio.sid: "{{ .Values.twilio.sid }}"
  twilio.token: "{{ .Values.twilio.token }}"
  twilio.number: "{{ .Values.twilio.number }}"
  mail.username: "{{ .Values.mail.username }}"
  mail.password: "{{ .Values.mail.password }}"
{{- end }}
