# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: gatewayserver-deployment
serviceName: gatewayserver
appLabel: gatewayserver
appName: gatewayserver

replicaCount: 1

image:
  repository: mrlearn/gatewayserver
  tag: v1.11

containerPort: 8072

service:
  type: LoadBalancer
  port: 8072
  targetPort: 8072

enable_sql: false
appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: true
otel_enabled: true
rabbit_enabled: false
kafka_enabled: false
redis_enabled: true
messageconfig_enabled: false
enable_notifications: false