{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.appLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
        - name: {{ .Values.appLabel }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
          {{- if .Values.appname_enabled }}
          - name: SPRING_APPLICATION_NAME
            value: {{ .Values.appName }}
          {{- end }}
          {{- if .Values.profile_enabled }}
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_PROFILES_ACTIVE
          {{- end }}
          {{- if .Values.config_enabled }}
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_CONFIG_IMPORT
          {{- end }}
          {{- if .Values.eureka_enabled }}
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          {{- end }}
          {{- if .Values.resouceserver_enabled }}
          - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
          {{- end }}
          {{- if .Values.otel_enabled }}
          - name: OTEL_SERVICE_NAME
            value: {{ .Values.serviceName }}
          - name: JAVA_TOOL_OPTIONS
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: JAVA_TOOL_OPTIONS
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: OTEL_EXPORTER_OTLP_ENDPOINT
          - name: OTEL_METRICS_EXPORTER
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: OTEL_METRICS_EXPORTER
          - name: OTEL_LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: OTEL_LOG_LEVEL
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: OTEL_EXPORTER_OTLP_PROTOCOL
          - name: OTEL_LOGS_EXPORTER
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: OTEL_LOGS_EXPORTER
          {{- end }}
          {{- if .Values.rabbit_enabled }}
          - name: SPRING_RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_RABBITMQ_HOST
          - name: SPRING_RABBITMQ_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_RABBITMQ_PORT
          - name: SPRING_RABBITMQ_USERNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_RABBITMQ_USERNAME
          - name: SPRING_RABBITMQ_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_RABBITMQ_PASSWORD
          {{- end }}
          {{- if .Values.kafka_enabled }}
          - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_KAFKA_BOOTSTRAP_SERVERS
          {{- end }}
          {{- if .Values.redis_enabled }}
          - name: SPRING_DATA_REDIS_CONNECT_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_DATA_REDIS_CONNECT_TIMEOUT
          - name: SPRING_DATA_REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_DATA_REDIS_HOST
          - name: SPRING_DATA_REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_DATA_REDIS_PORT
          - name: SPRING_DATA_REDIS_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_DATA_REDIS_TIMEOUT
          {{- end }}
          {{- if .Values.messageconfig_enabled }}
          - name: SPRING_CLOUD_STREAM_BINDERS_RABBITMQ_ENVIRONMENT_SPRING_RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_CLOUD_STREAM_BINDERS_RABBITMQ_ENVIRONMENT_SPRING_RABBITMQ_HOST
          - name: SPRING_CLOUD_STREAM_BINDERS_RABBITMQ_ENVIRONMENT_SPRING_RABBITMQ_USERNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_CLOUD_STREAM_BINDERS_RABBITMQ_ENVIRONMENT_SPRING_RABBITMQ_USERNAME
          - name: SPRING_CLOUD_STREAM_BINDERS_RABBITMQ_ENVIRONMENT_SPRING_RABBITMQ_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_CLOUD_STREAM_BINDERS_RABBITMQ_ENVIRONMENT_SPRING_RABBITMQ_PASSWORD
          {{- end }}
          {{- if .Values.enable_notifications }}
          - name: TWILIO_SID
            valueFrom:
              secretKeyRef:
                name: message-secrets
                key: twilio.sid
          - name: TWILIO_TOKEN
            valueFrom:
              secretKeyRef:
                name: message-secrets
                key: twilio.token
          - name: TWILIO_NUMBER
            valueFrom:
              secretKeyRef:
                name: message-secrets
                key: twilio.number
          - name: MAIL_USERNAME
            valueFrom:
              secretKeyRef:
                name: message-secrets
                key: mail.username
          - name: MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: message-secrets
                key: mail.password
          {{- end }}
          {{- if .Values.enable_sql }}
          - name: SPRING_DATASOURCE_URL
            value: {{ .Values.spring.datasource.url | quote }}
          - name: SPRING_DATASOURCE_USERNAME
            value: {{ .Values.spring.datasource.username | quote }}
          - name: SPRING_DATASOURCE_PASSWORD
            value: {{ .Values.spring.datasource.password | quote }}
          {{- end }}
  {{- end -}}