# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: message-deployment
serviceName: message
appLabel: message
appName: message

replicaCount: 1

image:
  repository: mrlearn/message
  tag: v1.11

containerPort: 9010

service:
  type: ClusterIP
  port: 9010
  targetPort: 9010

twilio:
  sid: ""
  token: ""
  number: ""

mail:
  username: ""
  password: ""

enable_sql: false
appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: true
rabbit_enabled: true
kafka_enabled: true
redis_enabled: false
messageconfig_enabled: true
enable_notifications: true