# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: loans-deployment
serviceName: loans
appLabel: loans
appName: loans

replicaCount: 1

image:
  repository: mrlearn/loans
  tag: v1.11

containerPort: 8090

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

spring:
  datasource:
    url: jdbc:mysql://loansdb-mysql.default.svc.cluster.local:3306/loansdb
    username: root
    password: root

enable_sql: true
appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
rabbit_enabled: true
kafka_enabled: false
redis_enabled: false
messageconfig_enabled: false
enable_notifications: false