# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: cards-deployment
serviceName: cards
appLabel: cards
appName: cards

replicaCount: 1

image:
  repository: mrlearn/cards
  tag: v1.11

containerPort: 9000

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

spring:
  datasource:
    url: jdbc:mysql://cardsdb-mysql.default.svc.cluster.local:3306/cardsdb
    username: root
    password: root

enable_sql: true
appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
rabbit_enabled: true
kafka_enabled: true
redis_enabled: false
messageconfig_enabled: false
enable_notifications: false